#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt-CI

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  release:
    types: [published]

jobs:

  build_openwrt:

    name: Build OpenWrt firmware

    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig libtinfo5
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir
          # ln -s -f /mnt/openwrt/build_dir/host ./build_dir/host
          # ln -s -f /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration file
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # 在 cat >> .config <<EOF 到 EOF 之间粘贴你的编译配置, 需注意缩进关系
          # 例如:

          cat >> .config <<EOF
          CONFIG_TARGET_ramips=y
          CONFIG_TARGET_ramips_mt7621=y
          CONFIG_TARGET_ramips_mt7621_DEVICE_xiaomi_mi-router-4a-gigabit=y
          CONFIG_BATMAN_ADV_BATMAN_V=y
          CONFIG_BATMAN_ADV_BLA=y
          CONFIG_BATMAN_ADV_DAT=y
          CONFIG_BATMAN_ADV_MCAST=y
          CONFIG_LIBCURL_COOKIES=y
          CONFIG_LIBCURL_FILE=y
          CONFIG_LIBCURL_FTP=y
          CONFIG_LIBCURL_HTTP=y
          CONFIG_LIBCURL_NO_SMB="!"
          CONFIG_LIBCURL_OPENSSL=y
          CONFIG_LIBCURL_PROXY=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_adbyby=y
          CONFIG_PACKAGE_batctl-default=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_dawn=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ip6tables-extra=y
          CONFIG_PACKAGE_ip6tables-mod-nat=y
          CONFIG_PACKAGE_iptables-mod-conntrack-extra=y
          CONFIG_PACKAGE_iptables-mod-ipopt=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kmod-batman-adv=y
          CONFIG_PACKAGE_kmod-crypto-crc32c=y
          CONFIG_PACKAGE_kmod-ip6tables-extra=y
          CONFIG_PACKAGE_kmod-ipt-conntrack-extra=y
          CONFIG_PACKAGE_kmod-ipt-ipopt=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-iptunnel4=y
          CONFIG_PACKAGE_kmod-lib-crc16=y
          CONFIG_PACKAGE_kmod-lib-crc32c=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_kmod-tun=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_libgcrypt=y
          CONFIG_PACKAGE_libgpg-error=y
          CONFIG_PACKAGE_libminiupnpc=y
          CONFIG_PACKAGE_libnatpmp=y
          CONFIG_PACKAGE_libstdcpp=y
          CONFIG_PACKAGE_luci-app-adbyby-plus=y
          CONFIG_PACKAGE_luci-app-argon-config=y
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_ShadowsocksR_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Shadowsocks_Libev_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Simple_obfs is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Socks5_Proxy is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Socks_Server is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Trojan is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Trojan-Go is not set
          # CONFIG_PACKAGE_luci-app-bypass_INCLUDE_Xray is not set
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_btrfs_progs is not set
          # CONFIG_PACKAGE_luci-app-diskman_INCLUDE_lsblk is not set
          CONFIG_PACKAGE_luci-app-easymesh=y
          CONFIG_PACKAGE_luci-app-fileassistant=y
          CONFIG_PACKAGE_luci-app-mwan3=y
          CONFIG_PACKAGE_luci-app-nat6-helper=y
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_PDNSD is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs is not set
          # CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
          # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Libev_Client is not set
          CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Xray=y
          CONFIG_PACKAGE_luci-app-store=y
          CONFIG_PACKAGE_luci-app-syncdial=y
          # CONFIG_PACKAGE_luci-app-unblockmusic is not set
          CONFIG_PACKAGE_luci-app-webadmin=y
          CONFIG_PACKAGE_luci-app-zerotier=y
          CONFIG_PACKAGE_luci-compat=y
          CONFIG_PACKAGE_luci-i18n-adbyby-plus-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-easymesh-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-mwan3-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-webadmin-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-zerotier-zh-cn=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_luci-theme-netgear=y
          CONFIG_PACKAGE_mwan3=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-local is not set
          # CONFIG_PACKAGE_shadowsocksr-libev-ssr-redir is not set
          CONFIG_PACKAGE_umdns=y
          CONFIG_PACKAGE_xray-core=y
          CONFIG_PACKAGE_zerotier=y
          CONFIG_XRAY_CORE_COMPRESS_UPX=y
          CONFIG_KERNEL_BUILD_USER="fanqi"
          EOF

          #
          # ===============================================================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8 || make download -j1 V=s
          rm -rf $(find ./dl/ -size -1024c)
          df -h

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h ./ --max-depth=1
          du -h /mnt/openwrt/ --max-depth=1 || true

      - name: Prepare artifact
        run: |
          mkdir -p ./artifact/firmware
          mkdir -p ./artifact/package
          mkdir -p ./artifact/buildinfo
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_buildinfo
          path: ./artifact/buildinfo/

      - name: Deliver package
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_package
          path: ./artifact/package/

      - name: Deliver firmware
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
                      NhAAAAAwEAAQAAAYEAxaP4zvZ7WqumoVyZjbLS07hyeeWZ/GbOGgrPEiYR6RGDRA0KMr8R
                      ojUQwOTxlvD7hslyjgDvRwVarUhLK73A5Lwb/qktLNOL47v7xUNasfGSk20/KcWLzC5C0p
                      e4RHd1fDDQRr00XfS87s7iTTRTEQNgNIR5b97a2bdSnE5mvgoeMqG4x2slWHbi0WckcjDV
                      LlhQdLtHPLoIwEXMHOVnYyq0wLoHm1USO2fo5fXH8cPqMmy4SkrTS2PtcOCr6htWjw7Meg
                      YPliXvMhajg3kbJh5nXxsiCCRvv1X6WFRkLR23UP3s+D/4xFAcLECtM5nPPDPvBBK8mA/S
                      RlOpH3joFOe84l7M5r7nJMD+gFbHdc6KQoNfHiTYrYL40Vfu4SjL7cjMfDCM+ouUf/DEy9
                      BlCLkqhFIXp4uIzdsXuiOKVBZEfatZX0yign3UyQL3n0jsDSZJXjGChG+iaCK04YyKGgre
                      +JmdLI44P2Jp+j/HSoxRbdEUUc6Xbl+VA2TVH5XPAAAFiHeX+Xd3l/l3AAAAB3NzaC1yc2
                      EAAAGBAMWj+M72e1qrpqFcmY2y0tO4cnnlmfxmzhoKzxImEekRg0QNCjK/EaI1EMDk8Zbw
                      +4bJco4A70cFWq1ISyu9wOS8G/6pLSzTi+O7+8VDWrHxkpNtPynFi8wuQtKXuER3dXww0E
                      a9NF30vO7O4k00UxEDYDSEeW/e2tm3UpxOZr4KHjKhuMdrJVh24tFnJHIw1S5YUHS7Rzy6
                      CMBFzBzlZ2MqtMC6B5tVEjtn6OX1x/HD6jJsuEpK00tj7XDgq+obVo8OzHoGD5Yl7zIWo4
                      N5GyYeZ18bIggkb79V+lhUZC0dt1D97Pg/+MRQHCxArTOZzzwz7wQSvJgP0kZTqR946BTn
                      vOJezOa+5yTA/oBWx3XOikKDXx4k2K2C+NFX7uEoy+3IzHwwjPqLlH/wxMvQZQi5KoRSF6
                      eLiM3bF7ojilQWRH2rWV9MooJ91MkC959I7A0mSV4xgoRvomgitOGMihoK3viZnSyOOD9i
                      afo/x0qMUW3RFFHOl25flQNk1R+VzwAAAAMBAAEAAAGAWB53vK8g6JhHvwIuZIMqhMNkJv
                      073tFnay0OjiTzL1tjj1/RADc4gX3vblGldYsUWlBPBwlbpeq5NzFYcrQz4MgOI0kCn03i
                      vTL/WkBhm5z9oUXAN7ugTPUDTinfOoeYljqdYizRwGJyKneLZqjBsIA00LWP/1T5dsDJ0G
                      8UV/7i3+hDHoajLAI1tu+pzFABfJxbovAtHuJDLJbyHqAZrJlJ5fQLmDIh4uK9cGpZL24O
                      aVUYBee+tYpkP0Os4sA02p3ZF8dM4DAgOtWMeP2oqFYhAze3PHVTppRLYcagMVKVMfHLHL
                      UZt4qGgkXYA1g26e9X0Gqrmv2Oo1u8LKo+TrLG+vfUNSmEEGYqKADBx0+lLuiIPY001tlm
                      SpFeQk2M2nEvKcgouvLL49R4sxhC2nUHN8X5IszWzRZx/SUo7HuCbGqrJI+nUPjg11HoHR
                      eqUb16bEMXLT9h7QWKYALhgy5W5qa+KiGcE78pfkOUZ7MigiaSjg+L+wUGdawy7llBAAAA
                      wH5qP31W/L8pVNBK0erqId1XSMiKh7GxkmZJPow/n3EKQhg82fvS+jrPbGSOLZRmoZ6bIl
                      iz2P7BZKlT5JBJZo/uI6gt8t1oUrPNDaXCLfI83iVpR2pk6TZGbamtUZyIao8cF4CugnPV
                      mI1j70wmtiYJ/Gsjqi3kkzP7xEkQIyq6Kd3MwNo+QYd3QlgOAtfebuP1CwZFoNExTMiyz6
                      lNnk1+Sj0ttp7bjwy/kI/9qwUyH87BHfdaLE2URc2LwIDGRwAAAMEA8PKJiOCAzmeBes0w
                      XuH3ybIfyS3TYm7DaSWAk7yQJJn0jb8N1UChsFnM7wG/548Drs1K/z4+qfFWCXXJ9slsii
                      +4XB1Kon9Abol3R7L65AckaZ/9kIB55Vtwi4NNO7CaOMCILZoLiK/6imC0sTInRWNV9NGf
                      yZMT29S5TDynBzgbXFU0KmQ2yXcdBWai5Tpn+ly04HvHJ01Y6VUOH4kyt11cYwEihKBqi0
                      f4Y0V5JyE2lA7EjTIUTxBWpH2fmNYHAAAAwQDR/NRB2ckrOfTtPWaKKmpp7Px5OBsPbxe2
                      vMbQCPg8E2vQC7KJx/LYWW6zw2AFtLTBLUrnICccQzKZ7I84DH/qB8OkTKkEYen6/V30c+
                      mn4Sa1sEI0i9prF3jRhVqCSVjaF21RbrVIi2UN2GzV4zEWkSVdumyBgYB1SmX3q1RE8aet
                      MILsIYtcyZWYD7PPrlvmbEFQsxLL/gX2B4PgAAioT/4/aCVHqecrQt/KzJV1z9+dOkw5FL
                      Jo7eCIcVBrD/kAAAAMZmFud2FuZ0BHNTEwAQIDBAUGBw==
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
